.PHONY: quality style

quality:
	pre-commit run --all-files

_setuppy:
	python -m pip install -qq poetry
	python -m poetry2setup > setup.py

	echo "# THIS FILE IS AUTO GENERATED BY make setuppy."
	python -m poetry export --without-hashes --with dev -f requirements.txt > requirements.txt

setup.py: _setuppy quality

lock:
	python -m poetry lock --no-update -v